In [1]:
#1, Handling arrays with NumPy 
#Single dimensional arrays
import numpy as np

# This creates our array
np_array = np.array([5, 10, 15, 20, 25, 30])
print("--0--")

# Gets the unique values
print(np.unique(np_array))
print("--1--")

# Calculates the standard deviation
print(np.std(np_array))
print("--2--")

# Calculates the maximum
print(np_array.max())
print("--3--")

# Squares each value in the array
print(np_array ** 2)
print("--4--")

# Adds the arrays together element wise
print(np_array + np_array)
print("--5--")

# The sum of the squares of the elements
print(np.sum(np_array ** 2))
print("--6--")

# Gives you the shape: (rows, columns)
print(np_array.shape)

--0--
[ 5 10 15 20 25 30]
--1--
8.539125638299666
--2--
30
--3--
[ 25 100 225 400 625 900]
--4--
[10 20 30 40 50 60]
--5--
2275
--6--
(6,)


In [2]:
#Two dimensional arrays
import numpy as np

# Create 2d array
print("--0--")
np_2d_array = np.array([[1,2,3], 
                        [4,5,6]])
print(np_2d_array)

# Calculate the transpose, which is when you swap the columns and rows.
print("--1--")
np_2d_array_T = np_2d_array.T
print(np_2d_array_T)

# Print the shape of the array as (number of rows, number of columns)
print("--3--")
print(np_2d_array.shape)

# Access elements in the 2d array by index. 
# First index is the row number
# Second index is the column number
# Index numbers start from 0
print("--4--")
print(np_2d_array[1,1])
print(np_2d_array[0,2])

--0--
[[1 2 3]
 [4 5 6]]
--1--
[[1 4]
 [2 5]
 [3 6]]
--3--
(2, 3)
--4--
5
3


In [3]:
#2, Important functionalities
#Calculating dot product
import numpy as np
np_array = np.array([5, 10, 15, 20, 25, 30])
dot_product = np.dot(np_array, np_array)
print(dot_product)

# references= https://en.wikipedia.org/wiki/Dot_product

2275


In [4]:
#Generating random values
import numpy as np

# Generage a single random number in range [0,1)
print("--0--")
print(np.random.rand())

# Generate a matrix of random numbers in range [0,1) with shape (3,2)
print("--1--")
print(np.random.rand(3,2))

--0--
0.4187389062791438
--1--
[[0.79110402 0.05099393]
 [0.14563127 0.24692526]
 [0.5868555  0.32590773]]


In [5]:
#You can also use randint()
import numpy as np

# Low=5, High=15, Size=2. Generate 2 values between 5 and 15 (exclusive)
print("--0--")
print(np.random.randint(5, 15, 2))

# Low=5, High=15, Size=(3,2). Generate a matrix of shape (3,2) with values between 5 and 15 (exclusive)
print("--1--")
print(np.random.randint(5, 15, (3,2)))

--0--
[ 6 11]
--1--
[[13  6]
 [ 9  9]
 [ 9  5]]


In [6]:
#Sampling the data
import numpy as np
array = np.array([1,2,3,4,5])

# Sample 10 data points with replacement. 
print("--0--")
print(np.random.choice(array, 10, replace=True))

# Sample 3 data points without replacement. 
print("--1--")
print(np.random.choice(array, 3, replace=False))

--0--
[1 5 1 2 5 3 4 4 5 5]
--1--
[1 5 4]


In [7]:
#Randomly shuffling values
import numpy as np

x = [1,2,3,4,5]  # Create a list of 5 elements
np.random.shuffle(x)  # Randomly shuffle the order of the elements in the list

print(x)

[2, 1, 5, 3, 4]


In [8]:
import numpy as np
np.random.seed(42)

In [13]:
import numpy as np
np.random.seed(42)
x = [1,2,3,4,5]  # Create a list of 5 elements
np.random.shuffle(x) # Randomly shuffle the order of the elements in the list

print(x)

[2, 5, 3, 1, 4]
